/aruco_node:
  ros__parameters:
    marker_size: 0.09
    aruco_dictionary_id: DICT_ARUCO_ORIGINAL
    image_topic: /image_raw
    camera_info_topic: /camera_info
    camera_frame: camera_rgb_optical_frame
